# .github/labview-ci.yml - LabVIEW CI configuration
# Updated by the Reconfigure workflow.
schemaVersion: 1
installedVersion: 4.16.3
configuredAt: 2026-09-25T15:47:46Z
source:
  repo: elijah286/LabVIEW-CI-with-Containers
  ref: v4.16.3
config:
  labviewVersion: "2026"
  os: [windows, linux]
  concurrency:
    maxParallel: 5
  container:
    use: latest
activities:
  - dashboard
  - masscompile
  - vi-analyzer
  - vidiff
  - snapshots
  - custom-image
  - snapshots-2
  - unit-tests
  - builds
  - sbom-generation

unitTests:
  thresholds:
    passedPercent:
      greenAtLeast: 100
      yellowAtLeast: 80
      redBelow: 80
  tools:
    caraya:
      enabled: true
      locations:
        - "tests/"
    lunit:
      enabled: false
      locations: []
    vi-tester:
      enabled: false
      locations: []
    utf:
      enabled: false
      locations: []
